// Package b2b_billing implements the B2B monthly billing report for the
// credits-system Q1 B2B2C grant path.
//
// # Source strategy (post b2b-billing-rules-rewrite hotfix, 2026-05-20)
//
// The report attributes each parent's monthly settlement amount based on
// two rules — neither of which reads membership_event.amount_cents directly.
// Instead, amounts are recomputed from product_type + months via
// membershipModel.PriceForMonths, which keeps the report robust against
// historical data bugs (doubling-era amount=0 rows, annual stored as
// 12×¥99 instead of ¥949, etc.).
//
//   - Rule A — first-month subscriber:
//     subscription.first_started_at ∈ [month_start, month_end). The user's
//     entire current total_months_purchased is settled this month, treated
//     as one grant action. Amount = PriceForMonths(total_months_purchased).
//     EXCEPTION: if the subscription has non-migration membership_event rows
//     in this month whose months sum equals total_months_purchased, build
//     per-event detail rows instead (preserves correct annual pricing when
//     the user separately bought 1-month + 12-month in the same month).
//
//   - Rule B — cross-month renewal:
//     subscription.first_started_at < month_start AND subscription.updated_at
//     ∈ [month_start, month_end) AND there exist non-migration membership_event
//     rows for this user in the month. Per-event detail rows built directly.
//
// Migration placeholder rows (idempotency_key LIKE 'migration-%') are always
// excluded — these were generated by the 2026-04-30 credit_package →
// membership_event migration as future-month occupancy markers for annual
// subscriptions, not real grant actions.
//
// Trials are handled separately by querying trial_grant directly (granted_at
// in the month, source = b2b_grant). Trial events in membership_event are
// not consulted because trial_grant.granted_at is more reliable.
//
// Boosters are completely excluded from settlement: they are self-purchased
// directly by users (扫码付款) and never owed by the parent account.
//
// # Pricing
//
// Pricing constants live in internal/pkg/model/membership/constants.go.
// The PriceForMonths helper centralises the annual-discount branch (¥949 for
// months==12) so both the grant write path and this read path stay aligned.
package b2b_billing

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"time"

	"numind-server/internal/numind/store"
	"numind-server/internal/pkg/model"
	membershipModel "numind-server/internal/pkg/model/membership"

	"gorm.io/gorm"
)

// migrationKeyPrefix identifies idempotency_key values written by the
// 2026-04-30 credit_package → membership_event migration script. Events with
// this prefix are placeholders (future-dated for annual subscriptions or
// historical fill-ins) and must NEVER count toward monthly settlement.
const migrationKeyPrefix = "migration-%"

// ErrNotParentAccount is returned by GetBillingReportForParent when the caller
// is not a parent account (User.ParentUserID != nil). Controllers map this to 403.
var ErrNotParentAccount = errors.New("b2b_billing: not a parent account")

// B2BBillingReport is the top-level response for a single month.
type B2BBillingReport struct {
	Month              string             `json:"month"`
	CutoverDate        time.Time          `json:"cutover_date"`
	Source             string             `json:"source"` // always "new_only" post-T9 (legacy_only / cutover_split removed)
	ByParent           []ParentBillingRow `json:"by_parent"`
	TotalAmountCents   int64              `json:"total_amount_cents"`
	TotalEventsCount   int                `json:"total_events_count"`
	ActiveParentsCount int                `json:"active_parents_count"`
}

// ParentBillingRow aggregates every grant made by one parent in the month.
type ParentBillingRow struct {
	ParentUserID   uint          `json:"parent_user_id"`
	ParentUsername string        `json:"parent_username"`
	GrantsCount    int           `json:"grants_count"`
	AmountCents    int64         `json:"amount_cents"`
	Details        []GrantDetail `json:"details"`
}

// GrantDetail is one billing event rendered for UI display.
type GrantDetail struct {
	ChildUserID   uint      `json:"child_user_id"`
	ChildUsername string    `json:"child_username"`
	ProductType   string    `json:"product_type"` // trial / monthly
	Months        int       `json:"months"`       // grant batch size for monthly; 0 for trial
	AmountCents   int64     `json:"amount_cents"`
	GrantedAt     time.Time `json:"granted_at"`
}

// ParentBillingReport is one parent's own monthly settlement view (self-service).
// Unlike B2BBillingReport it is flat (no by-parent grouping) since it is always
// scoped to a single parent.
type ParentBillingReport struct {
	Month            string        `json:"month"`
	ParentUserID     uint          `json:"parent_user_id"`
	GrantsCount      int           `json:"grants_count"`
	TotalAmountCents int64         `json:"total_amount_cents"`
	Details          []GrantDetail `json:"details"`
}

// grantEvent is the internal normalised representation for billing events.
type grantEvent struct {
	granterUserID uint
	childUserID   uint
	productType   string
	months        int
	amountCents   int64
	grantedAt     time.Time
}

// IB2BBillingBiz is the business interface.
type IB2BBillingBiz interface {
	GetBillingReport(ctx context.Context, month string) (*B2BBillingReport, error)
	GetBillingReportForParent(ctx context.Context, month string, parentUserID uint) (*ParentBillingReport, error)
}

type b2bBillingBiz struct {
	ds          store.IStore
	cutoverDate time.Time
}

// New constructs a b2bBillingBiz without an explicit cutover date.
// Post-T9 (credits-cleanup): chooseSource always returns new_only regardless of
// cutoverDate, so this constructor and NewWithCutover are functionally equivalent.
// Retained as a separate entry point for backward compat with existing callers/tests.
func New(ds store.IStore) IB2BBillingBiz {
	return &b2bBillingBiz{ds: ds}
}

// NewWithCutover constructs a b2bBillingBiz with an explicit cutover date.
func NewWithCutover(ds store.IStore, cutover time.Time) IB2BBillingBiz {
	return &b2bBillingBiz{ds: ds, cutoverDate: cutover}
}

// monthRegex enforces strict YYYY-MM format (zero-padded month).
var monthRegex = regexp.MustCompile(`^(\d{4})-(0[1-9]|1[0-2])$`)

// chooseSource always returns "new_only" after T9 cleanup.
//
// T9 (credits-cleanup): the legacy_only and cutover_split branches have been
// removed. Prod cutover_date=2026-04-20 + 0 B2B business pre-cutover means
// all relevant months are in new_only territory. The unused parameters
// (monthStart, monthEnd, cutover) are retained to keep callers unchanged.
func chooseSource(_, _, _ time.Time) string {
	return "new_only"
}

// GetBillingReport assembles the monthly B2B settlement report.
//
// Returns the per-parent breakdown of moxiaopai-owed amounts for memberships
// granted to child accounts in the given month. See package doc for the full
// Rule A / Rule B attribution logic.
func (b *b2bBillingBiz) GetBillingReport(ctx context.Context, month string) (*B2BBillingReport, error) {
	start, end, err := parseMonth(month)
	if err != nil {
		return nil, err
	}

	source := chooseSource(start, end, b.cutoverDate)

	events, err := b.computeBilling(ctx, start, end, nil)
	if err != nil {
		return nil, fmt.Errorf("GetBillingReport month=%s source=%s: %w", month, source, err)
	}

	return b.buildReport(ctx, month, source, events)
}

// computeBilling applies Rule A + Rule B + trial path to assemble the
// settlement events for the half-open [start, end) month window.
//
// granterUserID scopes the report to a single parent account:
//
//	nil  → all parent accounts (admin settlement report; unchanged behaviour)
//	&id  → only grants made by that parent (parent self-service report)
//
// When set, an additional `granter_user_id = ?` predicate is ANDed onto the
// Rule A / Rule B / trial queries so cross-parent rows never load into memory.
//
// Performance: bulk-loads membership_event rows for all candidate users in
// one query instead of issuing one query per subscriber (avoids N+1).
func (b *b2bBillingBiz) computeBilling(ctx context.Context, start, end time.Time, granterUserID *uint) ([]grantEvent, error) {
	var events []grantEvent

	// ── Rule A: first-month subscribers ──────────────────────────────────────
	//
	// subscription.first_started_at ∈ [start, end) AND source = b2b_grant AND
	// granter_user_id IS NOT NULL.
	var subsA []membershipModel.Subscription
	qA := b.ds.DB().WithContext(ctx).
		Where("source = ? AND first_started_at >= ? AND first_started_at < ? AND granter_user_id IS NOT NULL",
			membershipModel.SourceB2BGrant, start, end)
	if granterUserID != nil {
		qA = qA.Where("granter_user_id = ?", *granterUserID)
	}
	if err := qA.Find(&subsA).Error; err != nil {
		return nil, fmt.Errorf("computeBilling: query subs rule A: %w", err)
	}

	// ── Rule B: cross-month renewals ─────────────────────────────────────────
	//
	// subscription.first_started_at < start (granted in an earlier month) AND
	// subscription.updated_at ∈ [start, end) (touched this month) AND
	// source = b2b_grant AND granter_user_id IS NOT NULL.
	//
	// Per-event billing only — no subscription-truth fallback here because
	// total_months_purchased reflects the user's lifetime total, not the delta
	// added this month. If a user has updated_at in target month with no real
	// events, the update came from admin_calibration or similar non-grant
	// activity and contributes 0 to settlement.
	var subsB []membershipModel.Subscription
	qB := b.ds.DB().WithContext(ctx).
		Where("source = ? AND first_started_at < ? AND updated_at >= ? AND updated_at < ? AND granter_user_id IS NOT NULL",
			membershipModel.SourceB2BGrant, start, start, end)
	if granterUserID != nil {
		qB = qB.Where("granter_user_id = ?", *granterUserID)
	}
	if err := qB.Find(&subsB).Error; err != nil {
		return nil, fmt.Errorf("computeBilling: query subs rule B: %w", err)
	}

	// Bulk-load real (non-migration) events for ALL Rule A + Rule B users in
	// a single query, keyed by user_id. Replaces the prior per-user lookup
	// that issued one query per subscriber (N+1).
	allUserIDs := make([]uint64, 0, len(subsA)+len(subsB))
	for i := range subsA {
		allUserIDs = append(allUserIDs, subsA[i].UserID)
	}
	for i := range subsB {
		allUserIDs = append(allUserIDs, subsB[i].UserID)
	}
	eventsByUser, err := b.realEventsByUser(ctx, allUserIDs, start, end)
	if err != nil {
		return nil, err
	}

	// Rule A processing — uses 3-case logic (see package doc / case comments).
	for i := range subsA {
		sub := &subsA[i]
		// Defensive: SQL filter already guarantees GranterUserID != nil, but
		// guard against any future direct-write path that bypasses the filter.
		if sub.GranterUserID == nil {
			continue
		}
		realEvts := eventsByUser[sub.UserID]

		eventMonthsSum := 0
		for _, ev := range realEvts {
			eventMonthsSum += ev.months
		}

		switch {
		case len(realEvts) == 0:
			// Case 1: no real events → migration-only or no events; use subscription state.
			// Real-world example: 卉卉 (annual granted 2026-05-11, all 12 events
			// have migration- key from 4-30 credit_package migration).
			events = append(events, grantEvent{
				granterUserID: uint(*sub.GranterUserID),
				childUserID:   uint(sub.UserID),
				productType:   membershipModel.ProductTypeMonthly,
				months:        sub.TotalMonthsPurchased,
				amountCents:   membershipModel.PriceForMonths(sub.TotalMonthsPurchased),
				grantedAt:     sub.FirstStartedAt,
			})
		case eventMonthsSum > sub.TotalMonthsPurchased:
			// Case 2: events sum > total → operator manually adjusted total DOWN.
			// Respect the override; bill PriceForMonths(total).
			// Real-world example: sandy (events sum to 14 months, but operator
			// reduced subscription.total_months_purchased to 1).
			events = append(events, grantEvent{
				granterUserID: uint(*sub.GranterUserID),
				childUserID:   uint(sub.UserID),
				productType:   membershipModel.ProductTypeMonthly,
				months:        sub.TotalMonthsPurchased,
				amountCents:   membershipModel.PriceForMonths(sub.TotalMonthsPurchased),
				grantedAt:     sub.FirstStartedAt,
			})
		default:
			// Case 3: events sum ≤ total → use per-event detail. Preserves
			// per-event annual pricing for mixed monthly+annual in same month.
			events = append(events, realEvts...)
		}
	}

	// Rule B processing — per-event only.
	for i := range subsB {
		sub := &subsB[i]
		if sub.GranterUserID == nil {
			continue // defensive (see Rule A note)
		}
		events = append(events, eventsByUser[sub.UserID]...)
	}

	// ── Trial path ───────────────────────────────────────────────────────────
	//
	// trial_grant.granted_at ∈ [start, end) AND source = b2b_grant AND
	// granter_user_id IS NOT NULL.
	var trials []membershipModel.TrialGrant
	qT := b.ds.DB().WithContext(ctx).
		Where("source = ? AND granted_at >= ? AND granted_at < ? AND granter_user_id IS NOT NULL",
			membershipModel.SourceB2BGrant, start, end)
	if granterUserID != nil {
		qT = qT.Where("granter_user_id = ?", *granterUserID)
	}
	if err := qT.Find(&trials).Error; err != nil {
		return nil, fmt.Errorf("computeBilling: query trials: %w", err)
	}

	for i := range trials {
		t := &trials[i]
		if t.GranterUserID == nil {
			continue // defensive (see Rule A note)
		}
		events = append(events, grantEvent{
			granterUserID: uint(*t.GranterUserID),
			childUserID:   uint(t.UserID),
			productType:   membershipModel.ProductTypeTrial,
			months:        0,
			amountCents:   membershipModel.TrialPriceCents,
			grantedAt:     t.GrantedAt,
		})
	}

	// Stable ordering for deterministic output: by grantedAt ASC.
	sort.SliceStable(events, func(i, j int) bool {
		return events[i].grantedAt.Before(events[j].grantedAt)
	})

	return events, nil
}

// realEventsByUser bulk-loads non-migration subscription grant events for
// the given user IDs within [start, end), keyed by user_id. Returns an empty
// map when userIDs is empty (no DB call). Replaces an earlier per-user
// lookup pattern that issued N queries on monthly settlement.
//
// Each grantEvent's amountCents is recomputed via PriceForMonths (not read
// from the row's amount_cents column) for correctness against historical
// data bugs.
func (b *b2bBillingBiz) realEventsByUser(ctx context.Context, userIDs []uint64, start, end time.Time) (map[uint64][]grantEvent, error) {
	if len(userIDs) == 0 {
		return map[uint64][]grantEvent{}, nil
	}

	var mevs []membershipModel.MembershipEvent
	if err := b.ds.DB().WithContext(ctx).
		Where("user_id IN ? AND source = ? AND event_type IN ? AND occurred_at >= ? AND occurred_at < ? AND (idempotency_key IS NULL OR idempotency_key NOT LIKE ?)",
			userIDs,
			membershipModel.SourceB2BGrant,
			[]string{membershipModel.EventTypeSubGranted, membershipModel.EventTypeSubRenewed},
			start, end,
			migrationKeyPrefix,
		).
		Order("user_id ASC, occurred_at ASC").
		Find(&mevs).Error; err != nil {
		return nil, fmt.Errorf("realEventsByUser users=%d: %w", len(userIDs), err)
	}

	out := make(map[uint64][]grantEvent, len(userIDs))
	for i := range mevs {
		ev := &mevs[i]
		if ev.GranterUserID == nil {
			continue
		}
		months := 0
		if ev.Months != nil {
			months = int(*ev.Months)
		}
		out[ev.UserID] = append(out[ev.UserID], grantEvent{
			granterUserID: uint(*ev.GranterUserID),
			childUserID:   uint(ev.UserID),
			productType:   ev.ProductType,
			months:        months,
			amountCents:   membershipModel.PriceForMonths(months),
			grantedAt:     ev.OccurredAt,
		})
	}
	return out, nil
}

// lookupUsernames returns id→username for the given user IDs (Select id,username only).
func (b *b2bBillingBiz) lookupUsernames(ctx context.Context, ids []uint) (map[uint]string, error) {
	out := make(map[uint]string, len(ids))
	if len(ids) == 0 {
		return out, nil
	}
	var users []model.User
	if err := b.ds.DB().WithContext(ctx).
		Select("id, username").Where("id IN ?", ids).Find(&users).Error; err != nil {
		return nil, fmt.Errorf("lookupUsernames: %w", err)
	}
	for _, u := range users {
		out[u.ID] = u.Username
	}
	return out, nil
}

// GetBillingReportForParent assembles the self-service monthly settlement view
// for one parent account. Reuses computeBilling with a granter filter so the
// amounts are byte-for-byte consistent with the admin settlement report.
//
// Returns ErrNotParentAccount if parentUserID is not a parent account.
func (b *b2bBillingBiz) GetBillingReportForParent(ctx context.Context, month string, parentUserID uint) (*ParentBillingReport, error) {
	start, end, err := parseMonth(month)
	if err != nil {
		return nil, err
	}

	// Parent-account gate: query parent_user_id only (matches package query style;
	// avoids SELECT * coupling to the full user schema).
	var row struct {
		ParentUserID *uint `gorm:"column:parent_user_id"`
	}
	if err := b.ds.DB().WithContext(ctx).
		Table("user").Select("parent_user_id").
		Where("id = ?", parentUserID).
		Take(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotParentAccount
		}
		return nil, fmt.Errorf("GetBillingReportForParent: lookup user %d: %w", parentUserID, err)
	}
	if row.ParentUserID != nil {
		return nil, ErrNotParentAccount
	}

	events, err := b.computeBilling(ctx, start, end, &parentUserID)
	if err != nil {
		return nil, fmt.Errorf("GetBillingReportForParent month=%s parent=%d: %w", month, parentUserID, err)
	}

	report := &ParentBillingReport{
		Month:        month,
		ParentUserID: parentUserID,
		Details:      []GrantDetail{},
	}
	if len(events) == 0 {
		return report, nil
	}

	childIDSet := make(map[uint]struct{}, len(events))
	for _, e := range events {
		childIDSet[e.childUserID] = struct{}{}
	}
	childIDs := make([]uint, 0, len(childIDSet))
	for id := range childIDSet {
		childIDs = append(childIDs, id)
	}
	usernameByID, err := b.lookupUsernames(ctx, childIDs)
	if err != nil {
		return nil, fmt.Errorf("GetBillingReportForParent: %w", err)
	}
	for _, e := range events {
		report.Details = append(report.Details, GrantDetail{
			ChildUserID:   e.childUserID,
			ChildUsername: usernameByID[e.childUserID],
			ProductType:   e.productType,
			Months:        e.months,
			AmountCents:   e.amountCents,
			GrantedAt:     e.grantedAt,
		})
		report.TotalAmountCents += e.amountCents
	}
	report.GrantsCount = len(report.Details)
	return report, nil
}

// buildReport converts a flat []grantEvent into a B2BBillingReport.
func (b *b2bBillingBiz) buildReport(ctx context.Context, month, source string, events []grantEvent) (*B2BBillingReport, error) {
	if len(events) == 0 {
		return &B2BBillingReport{
			Month:       month,
			CutoverDate: b.cutoverDate,
			Source:      source,
			ByParent:    []ParentBillingRow{},
		}, nil
	}

	// Collect user IDs for username lookup.
	userIDSet := make(map[uint]struct{}, len(events)*2)
	for _, e := range events {
		userIDSet[e.granterUserID] = struct{}{}
		userIDSet[e.childUserID] = struct{}{}
	}
	userIDs := make([]uint, 0, len(userIDSet))
	for id := range userIDSet {
		userIDs = append(userIDs, id)
	}

	usernameByID, err := b.lookupUsernames(ctx, userIDs)
	if err != nil {
		return nil, fmt.Errorf("buildReport: %w", err)
	}

	// Group by parent.
	rowByParent := make(map[uint]*ParentBillingRow)
	var total int64

	for _, e := range events {
		row, ok := rowByParent[e.granterUserID]
		if !ok {
			row = &ParentBillingRow{
				ParentUserID:   e.granterUserID,
				ParentUsername: usernameByID[e.granterUserID],
				Details:        []GrantDetail{},
			}
			rowByParent[e.granterUserID] = row
		}
		row.GrantsCount++
		row.AmountCents += e.amountCents
		row.Details = append(row.Details, GrantDetail{
			ChildUserID:   e.childUserID,
			ChildUsername: usernameByID[e.childUserID],
			ProductType:   e.productType,
			Months:        e.months,
			AmountCents:   e.amountCents,
			GrantedAt:     e.grantedAt,
		})
		total += e.amountCents
	}

	rows := make([]ParentBillingRow, 0, len(rowByParent))
	for _, r := range rowByParent {
		rows = append(rows, *r)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].ParentUserID < rows[j].ParentUserID })

	return &B2BBillingReport{
		Month:              month,
		CutoverDate:        b.cutoverDate,
		Source:             source,
		ByParent:           rows,
		TotalAmountCents:   total,
		TotalEventsCount:   len(events),
		ActiveParentsCount: len(rows),
	}, nil
}

// --------------------------------------------------------------------------
// getLegacyEvents: archive table reader (preserved for historical audit tooling)
// --------------------------------------------------------------------------

// getLegacyEvents queries the legacy_credit_package_archive_20260515 table for
// B2B grant events (grant_source='b2b_grant') in the given [start, end) window.
//
// T11 (credits-cleanup): credit_package was archived to this table on 2026-05-15
// and then dropped. This function is wired to read the archive for any historical
// month that predates the cutover_date (2026-04-20). In practice prod had 0 B2B
// business before cutover, so this function will return empty for all pre-cutover
// months. It is preserved for completeness and future audit tooling.
//
// chooseSource() always returns "new_only" post-T9, so this function is not called
// from GetBillingReport. It remains available for:
//   - Direct audit queries via tooling
//   - Future reactivation of cutover_split mode if ever needed
//   - Historical month verification scripts
//
// TODO(T+future): Reactivate this code path when cutover_split mode is needed for
// backward-history queries (i.e. when chooseSource() returns "cutover_split"). At
// that point, wire it into GetBillingReport alongside computeBilling and remove the
// linter suppression on the function signature below.
func (b *b2bBillingBiz) getLegacyEvents(ctx context.Context, start, end time.Time) ([]grantEvent, error) { //nolint:unused // preserved for historical audit tooling; not called by GetBillingReport post-T9
	type archiveRow struct {
		GranterUserID uint
		UserID        uint
		Type          string // trial / subscription
		ActivatedAt   time.Time
	}

	var rows []archiveRow
	if err := b.ds.DB().WithContext(ctx).
		Table("legacy_credit_package_archive_20260515").
		Select("granter_user_id, user_id, type, activated_at").
		Where("grant_source = ? AND activated_at >= ? AND activated_at < ?",
			"b2b_grant", start, end).
		Order("activated_at ASC").
		Find(&rows).Error; err != nil {
		return nil, fmt.Errorf("getLegacyEvents: query archive: %w", err)
	}

	events := make([]grantEvent, 0, len(rows))
	for _, r := range rows {
		if r.GranterUserID == 0 {
			continue
		}
		// Reconstruct billing amounts from type (mirror of original getLegacyEvents logic).
		// Note: legacy table predates annual pricing; all subscriptions there were
		// 1-month grants priced at ¥99.
		var amountCents int64
		var productType string
		var months int
		switch r.Type {
		case "trial":
			amountCents = membershipModel.TrialPriceCents
			productType = membershipModel.ProductTypeTrial
		case "subscription":
			amountCents = membershipModel.MonthlyPriceCents
			productType = membershipModel.ProductTypeMonthly
			months = 1
		default:
			continue // skip booster (self_purchase only)
		}
		events = append(events, grantEvent{
			granterUserID: r.GranterUserID,
			childUserID:   r.UserID,
			productType:   productType,
			months:        months,
			amountCents:   amountCents,
			grantedAt:     r.ActivatedAt,
		})
	}
	return events, nil
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

// parseMonth validates and returns the half-open [start, end) bounds for "YYYY-MM".
func parseMonth(month string) (time.Time, time.Time, error) {
	m := monthRegex.FindStringSubmatch(month)
	if m == nil {
		return time.Time{}, time.Time{}, fmt.Errorf("parseMonth: invalid month format %q (expected YYYY-MM)", month)
	}
	y, _ := strconv.Atoi(m[1])
	mo, _ := strconv.Atoi(m[2])
	start := time.Date(y, time.Month(mo), 1, 0, 0, 0, 0, time.UTC)
	end := start.AddDate(0, 1, 0)
	return start, end, nil
}
