"""
example_with_chart.py — Invoice template + embedded chart PNG.

This example demonstrates the recommended pattern for combining a pre-existing
chart image (e.g. generated by the png-chart-author skill) with the invoice
HTML template:

1. Generate (or assume existence of) a PNG chart at /workspace/input/sales_chart.png
2. Render the invoice template with template_vars
3. The invoice template references the chart via <img src="sales_chart.png">;
   weasyprint resolves it via base_url="/workspace/input".

Run inside the sandbox (assumes matplotlib is available for chart generation):
    python /skills/pdf-from-html/examples/example_with_chart.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

# Allow running from the skill directory without install
sys.path.insert(0, str(Path(__file__).parent.parent))

from main import run


def _generate_sample_chart(output_png: str) -> None:
    """
    Generate a simple bar chart PNG for demonstration.
    Requires matplotlib (pre-installed in sandbox libs image).
    If matplotlib is unavailable, skip chart generation gracefully.
    """
    try:
        import matplotlib
        matplotlib.use("Agg")  # non-interactive backend
        import matplotlib.pyplot as plt

        months = ["1月", "2月", "3月", "4月", "5月"]
        revenue = [12.8, 14.1, 15.5, 17.2, 19.5]

        fig, ax = plt.subplots(figsize=(5, 3), dpi=150)
        bars = ax.bar(months, revenue, color="#1E293B", width=0.5)
        ax.set_ylabel("收入（万元）", fontsize=9)
        ax.set_title("月度收入趋势", fontsize=11, fontweight="bold")
        ax.set_ylim(0, 25)
        for bar, val in zip(bars, revenue):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.4,
                f"{val}",
                ha="center", va="bottom", fontsize=8,
            )
        ax.spines[["top", "right"]].set_visible(False)
        fig.tight_layout()
        plt.savefig(output_png, bbox_inches="tight")
        plt.close()
        print(f"  Chart generated: {output_png}")
    except ImportError:
        print("  matplotlib not available; skipping chart generation.")
        print("  The invoice template will render without the chart image.")


def main() -> None:
    chart_path = "/workspace/input/sales_chart.png"

    # Step 1: generate chart PNG (only if it does not already exist)
    if not os.path.exists(chart_path):
        print("Generating sample chart PNG...")
        _generate_sample_chart(chart_path)
    else:
        print(f"Using existing chart: {chart_path}")

    # Step 2: build invoice template_vars — include the chart via logo_path
    # (chart embedded in the notes section via extra_css + html_content approach
    #  for simplicity; in production, add chart <img> directly in template vars
    #  or use a custom html_content that wraps both invoice + chart).
    template_vars = {
        "invoice_number": "INV-2026-Q1-042",
        "company_name": "有数科技（北京）有限公司",
        "company_address": "北京市海淀区中关村大街 1 号",
        "company_tax_id": "91110108MA01XXXX00",
        "client_name": "某某新能源集团有限公司",
        "client_address": "上海市浦东新区张江高科技园区",
        "issue_date": "2026-05-24",
        "due_date": "2026-06-24",
        "items": [
            {
                "description": "莫小派 AI 工作台 — 企业版月订阅（2026-04）",
                "qty": 1,
                "unit_price": 2999.00,
            },
            {
                "description": "AI 积分加量包 × 5（5,000 积分，90 天有效）",
                "qty": 5,
                "unit_price": 299.00,
            },
            {
                "description": "SOP 定制开发服务（10 小时）",
                "qty": 10,
                "unit_price": 500.00,
            },
        ],
        "tax_rate": 0.06,
        "currency": "CNY",
        "notes": "付款方式：对公转账。账户名称：有数科技（北京）有限公司；开户行：招商银行北京中关村支行；账号：110920219910601",
        # logo_path is optional; set to None since we have no logo file here
        "logo_path": None,
    }

    # Step 3: Add a chart section via extra_css + extra HTML appended
    # We use html_content instead of template here to demonstrate embedding
    # the chart as a supplementary section after the invoice table.

    # First render the invoice template to get base HTML
    from helpers.template import render_template
    invoice_html = render_template("invoice", template_vars)

    # Inject the chart image before </body>
    chart_section = f"""
<div style="page-break-before: always; text-align: center; margin-top: 2em;">
  <h2 style="font-size: 13pt; color: #1E293B; margin-bottom: 1em;">附：月度收入趋势</h2>
  <img src="sales_chart.png"
       alt="月度收入趋势图"
       style="max-width: 80%; height: auto; border: 1px solid #E2E8F0; padding: 0.5em;">
</div>
"""
    invoice_html_with_chart = invoice_html.replace("</body>", chart_section + "\n</body>")

    # Step 4: render
    params = {
        "output_filename": "invoice_with_chart_INV-2026-Q1-042.pdf",
        "html_content": invoice_html_with_chart,
        "pdf_options": {
            "page_size": "A4",
            "orientation": "portrait",
            "base_url": "/workspace/input",
        },
    }

    result = run(params)
    print(json.dumps(result, ensure_ascii=False, indent=2))

    if result["success"]:
        print(f"\n✓ PDF 生成成功: {result['output_path']}")
        print(f"  文件大小: {result['output_size_bytes']:,} 字节")
        print(f"  页数: {result['page_count']}")
    else:
        print(f"\n✗ 生成失败: {result['error']}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
