-- Reverted: Claude thinking now uses parameter approach (thinking: {type: "adaptive"})
-- instead of model name suffix. provider_model_id stays as "claude-sonnet-4-6".
-- No DB changes needed for this approach.
