package memory

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"

	"numind-server/internal/numind/store"
	"numind-server/internal/pkg/log"
	"numind-server/internal/pkg/model"
)

// Digest is the spec §2 contract type for a single granularity-scoped activity
// digest for one user. V1.5 InjectDigests builds <temporal_context> blocks
// directly from the underlying model rows (UserMemoryDigestDaily / Weekly /
// Monthly / Quarterly) without going through this type — Digest is the
// abstraction documented in the spec for the future DigestGenerator API and
// V2 admin surfaces (raw digest export, cross-granularity timeline UI).
//
// Keeping this type defined preserves spec contract compliance and gives
// downstream consumers (V2 admin / reporting / data warehouse export) a
// granularity-agnostic shape to depend on without reaching into the per-table
// GORM models.
type Digest struct {
	UserID    uint
	Gran      Granularity
	Label     string   // human-readable period label, e.g. "昨日(2026-05-22)" / "上周(W21)"
	Summary   string   // generated summary text
	KeyTopics []string // optional extracted topics
}

// TemporalService is the Task 3.8 user-turn-side temporal digest injector.
//
// Lifecycle: stateless service constructed once at startup; no Start/Stop.
//
// Concurrency: every call goes through the underlying digestStore (DB only,
// no shared mutable state).
//
// Layer A only: every method operates on the agent **user themselves**.
// The injected digest describes that user's own cross-session activity
// (sessions, messages, extracted facts). Layer B (subject-scoped digests
// for the customer/dataset/document the user discusses) is V2 scope.
//
// D7 (B2B2C parent/child isolation): all queries take a single userID.
// Parent accounts cannot see child account digests.
type TemporalService interface {
	// InjectDigests scans userInput for time keywords (today / yesterday / 上周 /
	// 本月 / Q3 / ...), resolves matches to concrete digest periods, fetches
	// the corresponding rows from user_memory_digest_*, and renders them as
	// system-prompt-ready `<temporal_context …>` blocks (newline-separated).
	//
	// Returns "" (no injection) when:
	//   - userID == 0 (unauthenticated)
	//   - userInput contains no time keywords
	//   - all matched digests are missing in the DB (no rows yet)
	//
	// At most MaxKeywordMatches (=2) blocks are returned (spec §设计要点 cap).
	InjectDigests(ctx context.Context, userID uint, userInput string) string
}

// temporalService is the production TemporalService implementation.
type temporalService struct {
	digestStore store.IMemoryDigestStore
	// now is the clock seam — production wires time.Now; tests inject a fixed
	// clock to make period resolution deterministic.
	now func() time.Time
}

// TemporalOption configures a temporalService at construction.
type TemporalOption func(*temporalService)

// WithTemporalClock replaces the time.Now seam — TEST USE ONLY.
func WithTemporalClock(now func() time.Time) TemporalOption {
	return func(s *temporalService) { s.now = now }
}

// NewTemporalService constructs a TemporalService. digestStore is required.
// nil store → panic at construction (programming error; not a runtime
// error path).
func NewTemporalService(digestStore store.IMemoryDigestStore, opts ...TemporalOption) TemporalService {
	if digestStore == nil {
		panic("memory.NewTemporalService: digestStore must be non-nil")
	}
	s := &temporalService{
		digestStore: digestStore,
		now:         time.Now,
	}
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// InjectDigests is the public hot-path entry.
func (s *temporalService) InjectDigests(ctx context.Context, userID uint, userInput string) string {
	if s == nil || userID == 0 {
		return ""
	}
	matches := MatchTimeKeywords(userInput)
	if len(matches) == 0 {
		return ""
	}
	now := s.now()
	var blocks []string
	for _, m := range matches {
		rp, ok := ResolvePeriod(m, now)
		if !ok {
			log.Debugw("memory.temporal: unable to resolve period for match; skipping",
				"user_id", userID, "label", m.Label, "gran", string(m.Gran), "offset", m.Offset)
			continue
		}
		block, ok := s.fetchAndFormat(ctx, userID, m, rp)
		if !ok {
			continue
		}
		blocks = append(blocks, block)
	}
	if len(blocks) == 0 {
		return ""
	}
	return strings.Join(blocks, "\n\n")
}

// fetchAndFormat fetches one digest from the DB and renders it.
// Returns ("", false) when the digest is missing (not yet generated by cron) or
// when the row exists but its summary is empty (digest computed but content stripped).
// DB errors other than NotFound are logged and skipped (best-effort).
func (s *temporalService) fetchAndFormat(ctx context.Context, userID uint, m TimeKeywordMatch, rp ResolvedPeriod) (string, bool) {
	switch rp.Gran {
	case GranDaily:
		row, err := s.digestStore.GetDaily(ctx, userID, rp.Date)
		if err != nil {
			if !errors.Is(err, gorm.ErrRecordNotFound) {
				log.Warnw("memory.temporal: GetDaily failed; skipping",
					"user_id", userID, "date", rp.Date.Format("2006-01-02"), "error", err)
			}
			return "", false
		}
		if row == nil || strings.TrimSpace(row.Summary) == "" {
			return "", false
		}
		return formatDailyBlock(m, rp, row), true
	case GranWeekly:
		row, err := s.digestStore.GetWeekly(ctx, userID, rp.ISOYear, rp.ISOWeek)
		if err != nil {
			if !errors.Is(err, gorm.ErrRecordNotFound) {
				log.Warnw("memory.temporal: GetWeekly failed; skipping",
					"user_id", userID, "iso_year", rp.ISOYear, "iso_week", rp.ISOWeek, "error", err)
			}
			return "", false
		}
		if row == nil || strings.TrimSpace(row.Summary) == "" {
			return "", false
		}
		return formatWeeklyBlock(m, rp, row), true
	case GranMonthly:
		row, err := s.digestStore.GetMonthly(ctx, userID, rp.Year, rp.Month)
		if err != nil {
			if !errors.Is(err, gorm.ErrRecordNotFound) {
				log.Warnw("memory.temporal: GetMonthly failed; skipping",
					"user_id", userID, "year", rp.Year, "month", rp.Month, "error", err)
			}
			return "", false
		}
		if row == nil || strings.TrimSpace(row.Summary) == "" {
			return "", false
		}
		return formatMonthlyBlock(m, rp, row), true
	case GranQuarterly:
		row, err := s.digestStore.GetQuarterly(ctx, userID, rp.Year, rp.Quarter)
		if err != nil {
			if !errors.Is(err, gorm.ErrRecordNotFound) {
				log.Warnw("memory.temporal: GetQuarterly failed; skipping",
					"user_id", userID, "year", rp.Year, "quarter", rp.Quarter, "error", err)
			}
			return "", false
		}
		if row == nil || strings.TrimSpace(row.Summary) == "" {
			return "", false
		}
		return formatQuarterlyBlock(m, rp, row), true
	}
	return "", false
}

// ─── Block formatters ────────────────────────────────────────────────────────
//
// All formatters wrap the digest in a `<temporal_context data-internal="true">`
// XML block. The `data-internal="true"` attribute is stripped by Track 2
// Streaming Scrubber from any LLM echo (the tag is internal context, not user-
// facing). The opening `period=` attribute encodes a stable, machine-readable
// period identifier for downstream tooling.

func formatDailyBlock(m TimeKeywordMatch, rp ResolvedPeriod, row *model.UserMemoryDigestDaily) string {
	period := rp.Date.Format("2006-01-02")
	return wrapTemporalBlock(GranDaily, period,
		fmt.Sprintf("【%s(%s) 总结】", m.Label, period),
		row.Summary,
		row.KeyTopics)
}

func formatWeeklyBlock(m TimeKeywordMatch, rp ResolvedPeriod, row *model.UserMemoryDigestWeekly) string {
	period := fmt.Sprintf("%d-W%02d", rp.ISOYear, rp.ISOWeek)
	rangeStr := fmt.Sprintf("%s ~ %s",
		row.WeekStartDate.Format("2006-01-02"),
		row.WeekEndDate.Format("01-02"))
	return wrapTemporalBlock(GranWeekly, period,
		fmt.Sprintf("【%s(%s) 总结】", m.Label, rangeStr),
		row.Summary,
		row.KeyTopics)
}

func formatMonthlyBlock(m TimeKeywordMatch, rp ResolvedPeriod, row *model.UserMemoryDigestMonthly) string {
	period := fmt.Sprintf("%d-%02d", rp.Year, rp.Month)
	return wrapTemporalBlock(GranMonthly, period,
		fmt.Sprintf("【%s(%s) 总结】", m.Label, period),
		row.Summary,
		row.KeyTopics)
}

func formatQuarterlyBlock(m TimeKeywordMatch, rp ResolvedPeriod, row *model.UserMemoryDigestQuarterly) string {
	period := fmt.Sprintf("%dQ%d", rp.Year, rp.Quarter)
	return wrapTemporalBlock(GranQuarterly, period,
		fmt.Sprintf("【%s(%s) 总结】", m.Label, period),
		row.Summary,
		row.KeyTopics)
}

// wrapTemporalBlock emits a single <temporal_context> block. KeyTopics is
// optional — empty/missing JSON skips the "关键主题:" line.
func wrapTemporalBlock(gran Granularity, period, header, summary string, keyTopicsJSON datatypes.JSON) string {
	var b strings.Builder
	b.Grow(len(summary) + 256)
	b.WriteString(`<temporal_context data-internal="true" granularity="`)
	b.WriteString(string(gran))
	b.WriteString(`" period="`)
	b.WriteString(period)
	b.WriteString(`">`)
	b.WriteString("\n")
	b.WriteString(header)
	b.WriteString("\n")
	b.WriteString(strings.TrimSpace(summary))
	if topics := parseKeyTopicsList(keyTopicsJSON); len(topics) > 0 {
		b.WriteString("\n关键主题: ")
		b.WriteString(strings.Join(topics, ", "))
	}
	b.WriteString("\n</temporal_context>")
	return b.String()
}
