"""
helpers/pdf_meta.py — Lightweight PDF metadata extraction.

get_page_count: count pages in a weasyprint-generated PDF without any
additional Python dependency beyond the standard library.

Implementation strategy:
  Scan the raw PDF binary for occurrences of b"/Type /Page" or b"/Type/Page".
  This is accurate for PDFs generated by weasyprint (which emits well-formed
  PDF/1.7 with explicit page objects). It is NOT accurate for arbitrary PDFs
  (embedded font objects may contain the same bytes) — but since this skill
  only produces weasyprint output, it is sufficient for V1.5.

  If scanning fails for any reason (file not found, permission error, IO error),
  the function returns -1 without raising. The main flow must treat -1 as
  "unknown" and continue; page_count is informational only.

  Future: if we need to handle third-party PDFs, swap in pypdf and add it to
  required_libs. pypdf is not included now to keep the image lighter.
"""

from __future__ import annotations


def get_page_count(pdf_path: str) -> int:
    """
    Return the number of pages in a weasyprint-generated PDF file.

    Parameters
    ----------
    pdf_path:
        Absolute path to the PDF file.

    Returns
    -------
    int
        Number of pages (>= 1) if successfully counted, or -1 on any failure.
    """
    try:
        with open(pdf_path, "rb") as f:
            content = f.read()
    except Exception:
        return -1

    # weasyprint emits page objects as either "/Type /Page" (with space) or
    # "/Type/Page" (without space) depending on the PDF serialiser version.
    # Count both and return the larger value to be safe.
    count_with_space = content.count(b"/Type /Page")
    count_without_space = content.count(b"/Type/Page")
    total = max(count_with_space, count_without_space)
    return total if total > 0 else -1
